# Generated by Django 3.2.9 on 2021-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='https://github.com/Hazunanafaru/', max_length=200),
        ),
    ]
